import type { Metadata } from "next";
import Link from "next/link";

export function generateMetadata(): Metadata {
  return {
    title: "AI Review Response — Personalized Responses to Every Review | Reviewly",
    description: "AI review response tool that generates unique, personalized replies to customer reviews. Works for Google, Yelp, and any review platform.",
  };
}

export default function AIReviewResponse() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 py-16">
      <h1 className="text-4xl font-bold text-navy-900 mb-6">
        AI Review Response
      </h1>

      <p className="text-lg text-navy-700 mb-2">
        An AI review response is a reply to a customer review generated by artificial intelligence that reads like a real person wrote it. Reviewly creates AI review responses that reference the specific things customers mention — names, experiences, products, complaints — and adapts the tone based on the star rating.
      </p>
      <p className="text-lg text-navy-700 mb-8">
        No prompting. No editing templates. Paste a review or let Reviewly auto-detect new ones from your Google Business Profile. The AI writes the response. You approve it.
      </p>

      <a href="/#demo" className="btn-primary inline-block mb-12">
        See an AI Response — Free Demo
      </a>

      {/* IMAGE: Reviewly generating an AI review response — before and after */}
      <div className="rounded-lg overflow-hidden mb-12">
                <img
                  src="/images/screenshots/demo-review-pasted.webp"
                  alt="Review input and AI response output side by side - ai review response"
                  className="w-full h-auto rounded-lg"
                  loading="lazy"
                />
              </div>

      <h2 className="text-2xl font-bold text-navy-900 mb-4">
        What Makes a Good AI Review Response
      </h2>
      <ul className="list-disc pl-6 text-navy-700 space-y-2 mb-8">
        <li>References specific details from the review, not generic filler</li>
        <li>Matches the right tone — empathetic for complaints, warm for praise</li>
        <li>Keeps it short — 2-4 sentences, not a paragraph</li>
        <li>Avoids phrases like &ldquo;We appreciate your valuable feedback&rdquo;</li>
        <li>Sounds like the business owner, not a chatbot</li>
      </ul>

      {/* IMAGE: Example comparison — generic template response vs AI personalized response */}
      <div className="rounded-lg overflow-hidden mb-12">
                <img
                  src="/images/screenshots/demo-response-generated.webp"
                  alt="Generic vs AI-personalized review response - ai review response"
                  className="w-full h-auto rounded-lg"
                  loading="lazy"
                />
              </div>

      <h2 className="text-2xl font-bold text-navy-900 mb-4">
        Example: AI Response to a 1-Star Review
      </h2>
      <div className="card p-6 mb-4">
        <p className="text-sm font-semibold text-navy-500 mb-2">⭐ Review:</p>
        <p className="text-navy-700 italic">&ldquo;Ordered the steak medium rare and it came out well done. Sent it back and waited another 20 minutes. Ruined the evening.&rdquo;</p>
      </div>
      <div className="card p-6 mb-8">
        <p className="text-sm font-semibold text-emerald-600 mb-2">✅ AI Response:</p>
        <p className="text-navy-700">&ldquo;A well-done steak when you ordered medium rare is frustrating, and the 20-minute wait to fix it made it worse. That is not the experience we want anyone to have. We&apos;d like to make this right — reach out to us directly and dinner is on us next time.&rdquo;</p>
      </div>

      <h2 className="text-2xl font-bold text-navy-900 mb-4">
        Manual or Automatic
      </h2>
      <p className="text-navy-700 mb-4">
        <strong>Manual (free):</strong> Paste any review, get an AI response in 10 seconds. 5 free per month.
      </p>
      <p className="text-navy-700 mb-8">
        <strong>Automatic ($29-79/mo):</strong> Connect Google Business Profile. New reviews detected automatically. AI drafts responses. You approve or auto-post. Starter covers 1 location, Pro covers unlimited.
      </p>

      <a href="/#demo" className="btn-primary inline-block mb-12">
        See an AI Response — Free Demo
      </a>

      <div className="border-t border-navy-100 pt-8 mt-8">
        <p className="text-sm text-navy-500 mb-2">Related:</p>
        <div className="flex flex-wrap gap-4">
          <Link href="/uses/ai-review-responder" className="text-emerald-600 hover:text-emerald-700 text-sm font-medium">
            AI Review Responder →
          </Link>
          <Link href="/uses/ai-review-reply" className="text-emerald-600 hover:text-emerald-700 text-sm font-medium">
            AI Review Reply →
          </Link>
          <Link href="/uses/review-response-generator" className="text-emerald-600 hover:text-emerald-700 text-sm font-medium">
            Review Response Generator →
          </Link>
        </div>
      </div>
    </div>
  );
}
